//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bioscoop.Web.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bioscoop.Web.Resources.Languages.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string Date_ {
            get {
                return ResourceManager.GetString("Date:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre:.
        /// </summary>
        public static string Genre_ {
            get {
                return ResourceManager.GetString("Genre:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get ticket!.
        /// </summary>
        public static string Get_ticket_ {
            get {
                return ResourceManager.GetString("Get ticket!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hall:.
        /// </summary>
        public static string Hall_ {
            get {
                return ResourceManager.GetString("Hall:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ticket details.
        /// </summary>
        public static string Loading_ticket_details {
            get {
                return ResourceManager.GetString("Loading ticket details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail ticket.
        /// </summary>
        public static string Mail_ticket {
            get {
                return ResourceManager.GetString("Mail ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min age.
        /// </summary>
        public static string Min_age {
            get {
                return ResourceManager.GetString("Min age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum age:.
        /// </summary>
        public static string Minimum_age_ {
            get {
                return ResourceManager.GetString("Minimum age:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        public static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie details.
        /// </summary>
        public static string Movie_details {
            get {
                return ResourceManager.GetString("Movie details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Ticket.
        /// </summary>
        public static string Pay_Ticket {
            get {
                return ResourceManager.GetString("Pay Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playtime:.
        /// </summary>
        public static string Playtime_ {
            get {
                return ResourceManager.GetString("Playtime:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print ticket.
        /// </summary>
        public static string Print_ticket {
            get {
                return ResourceManager.GetString("Print ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on ticket code:.
        /// </summary>
        public static string Search_on_ticket_code_ {
            get {
                return ResourceManager.GetString("Search on ticket code:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search ticket.
        /// </summary>
        public static string Search_ticket {
            get {
                return ResourceManager.GetString("Search ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat.
        /// </summary>
        public static string Seat {
            get {
                return ResourceManager.GetString("Seat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string Show_Details {
            get {
                return ResourceManager.GetString("Show Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows.
        /// </summary>
        public static string Shows {
            get {
                return ResourceManager.GetString("Shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows this week.
        /// </summary>
        public static string Shows_this_week {
            get {
                return ResourceManager.GetString("Shows this week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows today.
        /// </summary>
        public static string Shows_today {
            get {
                return ResourceManager.GetString("Shows today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special:.
        /// </summary>
        public static string Special_ {
            get {
                return ResourceManager.GetString("Special:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time:.
        /// </summary>
        public static string Start_time_ {
            get {
                return ResourceManager.GetString("Start time:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succes, ticket found:.
        /// </summary>
        public static string Succes__ticket_found_ {
            get {
                return ResourceManager.GetString("Succes, ticket found:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket mailed..
        /// </summary>
        public static string Ticket_mailed_ {
            get {
                return ResourceManager.GetString("Ticket mailed.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket not found..
        /// </summary>
        public static string Ticket_not_found_ {
            get {
                return ResourceManager.GetString("Ticket not found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheelchair friendly:.
        /// </summary>
        public static string Wheelchair_friendly_ {
            get {
                return ResourceManager.GetString("Wheelchair friendly:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
